### ISSUE TITLE
Exception in thread QueueManagerThread

### ISSUE THREAD

**Issue by Amiralgaby** [flozz/yoga-image-optimizer#22]
### Bug description
A exception has been raised

#### What happened

The file has been optimized, but a Exception as been throwen (sorry for my english)

#### Error
```sh
Exception in thread QueueManagerThread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 376, in _queue_management_worker
    thread_wakeup.clear()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 93, in clear
    while self._reader.poll():
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 255, in poll
    self._check_closed()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 136, in _check_closed
    raise OSError("handle is closed")
OSError: handle is closed
```

#### Step to reproduce

* [ ] The bug is always reproducible
* [x] The bug seems to appear randomly

Steps to reproduce:
Just run an optimization (for a big file of 250ko) it took long time then finish with this error

### System information

* Operating system (with version): Ubuntu 20.04
* How did you installed the software?
    * [x] From PyPI (`pip3 install yoga-image-optimizer`)
    * [ ] From source
    * [ ] Windows Installer
    * [ ] Windows Zip
    * [ ] Other (please provide any useful information like command you use, a link to a documentation,...)

* YOGA Image Optimizer version: 1.1.1

**Comment by flozz** [comment]
Does this bug still exists in 1.2.x?

**Comment by flozz** [comment]
It was probably fixed when I fixed the concurrent.future bug with python < 3.9.

Thank you for the feedback! :)
