### ISSUE TITLE
Corrupted images are not handled properly

### ISSUE THREAD

**Issue by flozz** [flozz/yoga-image-optimizer#27]
#### What happened

If there is a corrupted image when dropping a bunch of file on the app window, the import process crash and other images are not imported.

#### What was expected

When a corrupted image is imported,

* the app must continue importing other image after encountering the corrupted one
* and at the end of the import, a message should warn the user about the corrupted image(s)

#### Step to reproduce

* [x] The bug is always reproducible
* [ ] The bug seems to appear randomly

Steps to reproduce:

Just drag & drop some image with one corrupted.

### System information

* Operating system (with version): Ubuntu 22.04
* How did you installed the software?
    * [ ] From PyPI (`pip3 install yoga-image-optimizer`)
    * [ ] From source
    * [ ] Windows Installer
    * [ ] Windows Zip
    * [x] Other: working from the `master` branch

* YOGA Image Optimizer version: `master` (`c60c29a510716cdb603d12f6e668d4b767b8b622`)

Stack trace:

```
Traceback (most recent call last):
  File "yoga_image_optimizer/main_window.py", line 422, in _on_drag_data_received
    _add_path([path])
  File "yoga_image_optimizer/main_window.py", line 417, in _add_path
    app.add_image(path)
  File "yoga_image_optimizer/application.py", line 183, in add_image
    preview=helpers.preview_gdk_pixbuf_from_image(image),
  File "yoga_image_optimizer/helpers.py", line 92, in preview_gdk_pixbuf_from_image
    image_rgba.paste(image)
  File "__env__/lib/python3.10/site-packages/PIL/Image.py", line 1617, in paste
    im.load()
  File "__env__/lib/python3.10/site-packages/PIL/ImageFile.py", line 276, in load
    raise_oserror(err_code)
  File "__env__/lib/python3.10/site-packages/PIL/ImageFile.py", line 71, in raise_oserror
    raise OSError(message + " when reading image file")
OSError: broken data stream when reading image file
```
---

Related issue: #14

**Comment by flozz** [comment]
Errors are now handled on optimization too:

![image](https://user-images.githubusercontent.com/971438/192768842-bda24a89-e249-469f-a05b-988397399d58.png)
