### ISSUE TITLE
assets are not installed while installing from pypi package

### ISSUE THREAD

**Issue by jbghoul** [flozz/yoga-image-optimizer#3]
```
$ yoga-image-optimizer 
Traceback (most recent call last):
  File "/home/jbghoul/dev/yoga-image-optimizer/__env__/lib/python3.8/site-packages/yoga_image_optimizer/application.py", line 81, in do_activate
    self._main_window = MainWindow(self)
  File "/home/jbghoul/dev/yoga-image-optimizer/__env__/lib/python3.8/site-packages/yoga_image_optimizer/main_window.py", line 20, in __init__
    icon=GdkPixbuf.Pixbuf.new_from_file(
gi.repository.GLib.Error: g-file-error-quark: Impossible d’ouvrir le fichier « /home/jbghoul/dev/yoga-image-optimizer/__env__/lib/python3.8/site-packages/yoga_image_optimizer/data/images/icon_64.png » : Aucun fichier ou dossier de ce type (4)
```

**Comment by flozz** [comment]
Fixed in `v0.99.2`, thanks !
